from time import sleep

print("Loading...")
sleep(4)
print("Load successful. Starting TARDIS EX12...")
sleep(3)
print("Checking files...")
sleep(0.99)
print("Running Python commands...")
sleep(5)
print("Devicename = 'TARDIS EX12 PLATINUM. I-FEATURES: TARDI1233 CONNECTION, TARDIS UPGRADED PLATINUM EDITION, BETA LANDROVER CONNECTION, AX12 INPUT SYSTEM.")
sleep(0.5)
print("--------------------------------------------------------ONLINE--------------------------------------------------------------")
print("WELCOME TO TARDIS EX12, USING THE AX12 INPUT SYSTEM.")
print("ALL PREVIOUS WORLDS FEATURED IN 'TARDIS' HAVE BEEN MOVED TO 'OLDWORLD_SELECTION'. TO ACESS 'OLDWORLD_SELECTION' PLEASE TYPE 'OLDWORLD_SELECTION.py' AND HIT ENTER. IF YOU DO NOT, YOU WILL NOW HAVE TO HIT ENTER AND YOU WILL SEE A NEW RANGE OF WORLDS.")
whatnext = input()
if whatnext == "":
    print("""












































""")
    print("LIST OF NEW WORLDS:")
    print("1: EARTH-X-B, CLUSTER IX, LACTOSE WAY. 2: HOMEBASE REVAMPED. 3: GALACTIX-B9, CLUSTER IX, LACTOSE WAY, ORBITING STAR: GALACTIX. 4: SUPERNOVINO-X")
    print("(#1 e-x-b, #2 hbr, #3 g-b9, #4:s-novino-x)")
    planetselect = input()
    if planetselect == "e-x-b":
        print("EARTHERIA XENOVIA 46 BOLNOVIA, OR, MORE COMMONLY KNOWN AS, PLANET EARTH-X-B, IS A SMALL, ISOLATED EXOPLANET FOUND ORBITING A COLD, DESOLATE PLANET CALLED EARTHERIA XENOVIA 46, IS SURPRISINGLY HABITABLE, UNLIKE IT'S CLOSE SISTER PLANET. THIS EXOPLANET HAS LOTS OF DIFFERENT OUTPOSTS: OUTPOST X, OUTPOST JADE, OUTPOST CX AND OUTPOST 46. WHEN THE TARDIS EX12 HAS LANDED, PLEASE REMEMBER TO PUT ON YOUR SUPER WARMING SUIT, AS THE TEMPARTURE HERE AVERAGES AROUND -42 DEGRESS CELSIUS (-43.6 FAHRENHEIT). WHEN YOU EXIT THE TARDIS EX12, PLEASE WALK SLOWLY TO THE OUTPOST THAT YOU LAND AT, AS WALKING TO FAST WOULD SEND ALL OF THE BLOOD TO YOUR BRAIN AND YOUR BODYPARTS WOULD FALL OFF. GOOD LUCK!")
        sleep(55)
        print("PREPARING FOR TAKEOFF. THIS PROCESS WILL TAKE A MINIMUM OF 10 SECONDS.")
        
        
